//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientPortConfigFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientPortConfigFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.ClientPortConfigFile", typeof(ClientPortConfigFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9960.
        /// </summary>
        public static string barometar1 {
            get {
                return ResourceManager.GetString("barometar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9961.
        /// </summary>
        public static string barometar2 {
            get {
                return ResourceManager.GetString("barometar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9970.
        /// </summary>
        public static string senzorToplote1 {
            get {
                return ResourceManager.GetString("senzorToplote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9971.
        /// </summary>
        public static string senzorToplote2 {
            get {
                return ResourceManager.GetString("senzorToplote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9980.
        /// </summary>
        public static string senzorZvuka1 {
            get {
                return ResourceManager.GetString("senzorZvuka1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9981.
        /// </summary>
        public static string senzorZvuka2 {
            get {
                return ResourceManager.GetString("senzorZvuka2", resourceCulture);
            }
        }
    }
}
